[project]
name = "environment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lev", email = "lev@email.com" }
]
requires-python = ">=3.14.4"
dependencies = [
    "argparse>=1.4.0",
    "ipython>=9.17.1",
    "kagglehub[pandas-datasets]>=0.1",
    "pandas>=3.0.6",
    "pathlib>=1.0.1",
    "scikit-learn>=1.9.1",
    "xgboost>=3.4.1",
]

[project.scripts]
environment = "environment:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
